### ISSUE TITLE
DB migration - Solution #3

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1057]
To be added

**Comment by klesh** [comment]
The priority of this issue has been brought up, due to ee is planning to release with DevLake on next iteration.

**Comment by klesh** [comment]
Based on previous discussion, most of us tend to the following solution:
Solution #3: implement go-migrate functionality by using gorm.Migrator without go.AutoMigrate
How it works
1. Write migration scripts in Golang
2. Register them all to framework
3. Framework executes unexecuted scripts one by one
Pros
1. Easy to implement on Framework level
2. Easy to understand
Cons
1. It's very tedious to write every single migration script and error-prone, like missing tables/columns and typos... We have 67 tables now, and you can bet on more to come.
2. Migration script auto-generation becomes kind of mandatory in order to reduce error and work hours, but it's not an easy task.
