### ISSUE TITLE
Add more notification for pipeline status change

### ISSUE THREAD

**Issue by narrowizard** [merico-dev/lake#1072]
## Description
Now we have notification when pipeline is finished (both completed or failed), but no notification for other status changing (eg: status from `created` to `running`. We want to subscribe more accurency status change notification to track these pipelines.

## Describe the solution you'd like
Lake should send notification once a pipeline's status has changed. If possible. it is better to send notification too when process updated.

## Has the Feature been Requested Before?
No

## Additional context
Related to #452

**Comment by warren830** [comment]
I think we can resolve this when we are working on task management

**Comment by narrowizard** [comment]
Nice, can you tell how to subscribe pipeline(maybe workflow) events, when we are ready to move to task management system?

**Comment by klesh** [comment]
Right now, pipeline is scheduled right after `created`, hence `created` is a short lived status, no point to receive such a status notification. and we dont have any other possible `status` at this point. 

And due to the fact that this issue had been around for quite a while, no body ever mentioned it once,  nor did it cause any problem.
I'm closing it for now, feel free to re-open and prove you point.
