### ISSUE TITLE
Automated QA Tests for data integrity

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#1083]
## Description
Right now, we only test data integrity manually. This can cause us problems since we sometimes miss things manually. 

## Describe the solution you'd like
I would like an automated solution to test out our data that accomplishes the following

How the tests can run:
- [ ] Can be run on each check in of CI
- [ ] Checks against static data that does not change. (Sample repos we make or fakes JSON responses)
- [ ] Verifies that the total records we expect in every table exist by `count(*)`
- [ ] Verifies that the correct data and fields are captured (Select x from y where x.a != null) etc.
- [ ] Sample data can be updated easily

Possible problems we can run into:
- If we run this often, we will soon run out of api rate limits, IE if this is a part of CI

How the code can work:
1. (Best) Nginx can serve up sample JSON to us on any route that will copy the API we are trying to emulate.
- The tests will run of off a .env.test file that points to our nginx servers for the github base api url etc.
- We will have a new docker-compose.test.yml that will host our nginx server and sample JSON directory
- Developers can use this to develop faster locally and test code more efficiently

## Has the Feature been Requested Before?
No

## Describe alternatives you've considered
1. Manual Testing. Too slow and time consuming for our small team
2. (Bad, @klesh will not approve 😃 )We can have a flag in the code to tell it that, in testing mode, we will fetch from a local file system of JSON to get data

**Comment by joncodo** [comment]
I would like a review of this from @klesh @kevin-kline and @hezyin . Please thumb it up or down if approved or rejected

**Comment by klesh** [comment]
how about we setup some dedicated instances instead of fake response, like repositories only for testing on github/gitlab...
because fake JSON is very time consuming to do so, and api could change its response at any point of time.
plus, its hard to cover every cases, response might vary depends on user setting stuff like that.
Often, document tends to not telling which fields might be missing and on what circumstance would that be happening.
I think we do it on real environment with dedicated instance will be easier for us to setup and debug, like, we can log into those  instance and see what was wrong.

**Comment by joncodo** [comment]
We wont make the fake json by hand. It will be made automatically from api responses from the real api

**Comment by Startrekzky** [comment]
Already merged.
