### ISSUE TITLE
have re-enter jira source setting for `epic key` setup when creating new source on `config-ui`

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1246]
## Describe the bug
When creating new Jira Source, no `epic key` setting, that is ok
![image](https://user-images.githubusercontent.com/61080/154908804-e9fd9773-264c-4553-a412-41d7c822e69c.png)
But when I hit `Save Connection` button, it brings me to listing page
![image](https://user-images.githubusercontent.com/61080/154908915-e8bdf9a4-a637-4d9d-aa49-93a3a8b83538.png)
So I have click on newly created source entry in order to complete the whole setup
![image](https://user-images.githubusercontent.com/61080/154909034-aeba4d8c-5d7f-4717-9910-46ce45376ca0.png)

## Expected behavior
Can we stay on detail page instead of going back to listing page?

**Comment by e2corporation** [comment]
@klesh We need to save a connection first before allowing  Type mappings to be defined. The Type mappings are only available live from the API. If no valid connection exists, the type mapping selectors will have no data to drive them. I think what you are expecting is user is routed to The Connection Details/Edit Screen instead of the Manage Connections page.

**Comment by klesh** [comment]
@yumengwang03  you may want to take a look at this problem
