### ISSUE TITLE
filtering keyboard wont go away for jira configuration on `config-ui`

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1250]
## Describe the bug
Have to manualy remove keyword after selecting what I needed
![image](https://user-images.githubusercontent.com/61080/154920750-c1c8dce4-39c6-46c5-9ca4-c0cfb1c70320.png)

## Expected behavior
Keyword got removed after selection

**Comment by klesh** [comment]
Should not have duplicate items
![image](https://user-images.githubusercontent.com/61080/154929390-d9178e9e-1d3e-40b2-b5b6-01e3bd7bad3e.png)

**Comment by e2corporation** [comment]
@klesh This means you have a duplicate field defined in your JIRA Instance. The duplicate field should be removed from JIRA. The UI already prevents the same Tag from being selected twice.

**Comment by e2corporation** [comment]
@klesh JIRA doesn't appear to allow duplicate Issue Types to be created -- can you confirm why you have a duplicated Story tag on your JIRA Instance?

<img width="602" alt="Screen Shot 2022-02-21 at 11 24 14 AM" src="https://user-images.githubusercontent.com/1742233/154993804-37b85bf5-ce41-4717-b91e-ec9b893a77fa.png">

**Comment by e2corporation** [comment]
This may get moved to `v0.10.0` release since it's more of a usability trait than a code issue. The text input acts like a search/filter to assist with selecting a specific tag. The default behavior of the component does not clear what you type after making a selection, because only a *Tag* selected will be stored. Any user-type text will not get saved accidentally if it isn't erased anyway, so this won't necessarily cause a problem.

I will look into a way to enhance this to see if we can clear the search terms after a selection is made.

**Comment by e2corporation** [comment]
It turns out the core component will take care of clearing the query, I will get a small fix implemented.

```
# BlueprintJS MultiSelect State Interface 
export interface IMultiSelectExampleState {
    allowCreate: boolean;
    createdItems: IFilm[];
    fill: boolean;
    films: IFilm[];
    hasInitialContent: boolean;
    intent: boolean;
    items: IFilm[];
    openOnKeyDown: boolean;
    popoverMinimal: boolean;
    resetOnSelect: boolean; <------- This should clear the search query on select.
    tagMinimal: boolean;
}
```
