### ISSUE TITLE
create pipeline / advaced mode not working when built and run via docker

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1251]
## Describe the bug
This json editor is working find on dev mode,
but when built and packed as docker image, it stopped working, the cursor went to some weird place, practically unable to do any thing
![image](https://user-images.githubusercontent.com/61080/154924995-338ff679-d102-48c0-b438-1de97bbc3e18.png)

## To Reproduce
1. docker-compose build config-ui
2. docker-compose up -d
3. Open config-ui on browser, create pipeline in advanced mode

## Expected behavior
able to edit json when built and packed as docker image

**Comment by klesh** [comment]
This is what it looks like when `selected all`
![image](https://user-images.githubusercontent.com/61080/154930978-f4ab9607-595c-43a0-8843-6dc86f0c3534.png)

**Comment by e2corporation** [comment]
After much troubleshooting there appears to be a problem with the package `@uiw/react-textarea-code-editor` and the application in **Built/Minified** mode. This will require more troubleshooting in `v0.10.0`, for now we will downgrade the code editor to a basic textarea editor in order to restore functionality.
