### ISSUE TITLE
Nav item "triggers" in config-ui not show always

### ISSUE THREAD

**Issue by likyh** [merico-dev/lake#1265]
## Describe the bug
Nav item "triggers" in config-ui not show always

## Screenshots
![sukopWJg2j](https://user-images.githubusercontent.com/3294100/155113941-1824277a-f400-4ee1-b6a1-e7991358b3ff.png)

**Comment by e2corporation** [comment]
@likyh @klesh Since `Advanced Mode` has been added to the **Create Pipeline** workflow we can remove Triggers from the Sidebar menu. However,  this appears to be a build/caching related issue if Triggers is missing on your end -- if possible, please produce exact steps you are taking to make the "Triggers" disappear. Triggers was added again to the SidebarMenu for at least 2 releases now, and there is no conditional logic wrapped around it that would make it hide or show.

**Comment by klesh** [comment]
resolved
