### ISSUE TITLE
collecting Jira change log

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#141]
Requirement lead time should be broken down by issue status, then we could find out in which state the requirement stays for the most time.
The breakdown metrics will also be mentioned in Jinglei's demo.

**Comment by joncodo** [comment]
I am closing this for now until we get some better details on what we are looking to achieve. 

## Questions

1. Does this mean that we want to implement lead time as it is now in the `main` branch?
2. Are there any new requirements?
3. Is it only a task of switching this to TS instead of JS?
4. Is there any way to work on this now or do we need to move this to a larger ticket of "implement Jira collection"?

**Comment by Startrekzky** [comment]
> I am closing this for now until we get some better details on what we are looking to achieve.
> 
> ## Questions
> 1. Does this mean that we want to implement lead time as it is now in the `main` branch?
> 2. Are there any new requirements?
> 3. Is it only a task of switching this to TS instead of JS?
> 4. Is there any way to work on this now or do we need to move this to a larger ticket of "implement Jira collection"?

Cool. I will elaborate on this later.
