### ISSUE TITLE
Gitlab data collection failure

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#1449]
## Describe the bug

GitLab data collection fails with two different error messages.

## To Reproduce

The environment is GitLab enterprise edition 14.8.2.

## Screenshots

<img width="1135" alt="Screen Shot 2022-04-06 at 11 10 18 PM" src="https://user-images.githubusercontent.com/2908155/162131815-9cd1aa13-fae9-4d7a-924c-7575fe1de4b4.png">

**Comment by klesh** [comment]
The first error appear to be caused by Network Connectivity issue, context deadline exceeded suggests it was timeouted.

The second error likely to be the same kind of problem, which the `res` from line 43 being `nil` and `err` being NOT `nil`, causing `nil pointer` problem from line 46, which is a bug but not the root cause of our problem here.

I'm guessing the Gitlab server somehow overloaded during collection process, we need devlake log for further investigation.

BTW, running mulitple collections against same Connection in parallel is not recommended, this would likely to cause rate limit exceeding, or overload the server if rate limit was disabled on the gitlab server. I would suggest that we collect them in sequential order:

```json
[
  [
    {
        "plugin":"gitlab",
        "options":{
            "projectId":13
        }
    }
  ],
  [
    {
        "plugin":"gitlab",
        "options":{
            "projectId":14
        }
    }
  ]
]
```

**Comment by warren830** [comment]
already fixed
