### ISSUE TITLE
config-ui: still showing add connections page in an instance set up in k8s

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1586]
## Describe the bug
After clicking 'GitHub' in data integrations page, the page jumped to 'add a connection' page, which doesn't follow the design.

## To Reproduce
1. Go to config-ui, click 'GitHub' icon
2. See the page

## Screenshots
![image](https://user-images.githubusercontent.com/14050754/163435591-aa225152-5423-4bea-b25c-ebadb5dc031f.png)

**Comment by e2corporation** [comment]
@Startrekzky This is a non-issue, how did you access this page? Did you manually type an add connection URI in the browser path? GitHub is not multi-source and therefore cannot support multiple connections. This page is disabled and not accessible by GitHub.

<img width="1096" alt="Screen Shot 2022-04-14 at 12 09 59 PM" src="https://user-images.githubusercontent.com/1742233/163430097-186331e0-7a56-4c6a-8458-a599395030ed.png">

**Comment by klesh** [comment]
This due to nginx resolver must be FQDN when deployed to k8s, causing config-ui unable to talk to devlake service (the problem appears only on new k8s instance)
I had fixed the instance on k8s, need some more work to finish up the PR.
However, I notice the offline prompt doesn't seem to be working when server side responsed 502?
