### ISSUE TITLE
Config UI - Job Triggers (Tasks)

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#620]
## Description
Triggers need to be re-activated within config-ui.

**Comment by kevin-kline** [comment]
My current understanding of this ticket is that we want to have a tab in the Sidebar that takes us to a page which displays all the tasks we can get from the DB in a table. I will work on that assumption, unless anyone has any comments / suggestions / ideas.

Feel free to correct me @e2corporation @joncodo

**Comment by klesh** [comment]
Due to the fact that `expressjs` had been removed from `config-ui` the old `/api/triggers/pendings` wont work anymore.
We can still utilizing `Triggers` page by update this endpoint o devlake `tasks.Get` route, because the origin one do nothing more than forwarding the requests, this is the fast way to go.

In the future we could develop sth more sophisticated for the same purpose.

The trigger implementation is bad because it is sending too much requests to devlake, flush out the useful logging and quite annoying. But it help user go through the process little bit smoother, one can observe the progress of all plugins and then see a "Go to Grafana" button after all tasks are done.

The new method should follow the same steps: trigger / progress / go to grafana .  and with a better implementation. Which is not a easy task, so i suggest we do the fast way first, and then work on the new method on next iter.

**Comment by kevin-kline** [comment]
> Due to the fact that `expressjs` had been removed from `config-ui` the old `/api/triggers/pendings` wont work anymore. We can still utilizing `Triggers` page by update this endpoint o devlake `tasks.Get` route, because the origin one do nothing more than forwarding the requests, this is the fast way to go.
> 
> In the future we could develop sth more sophisticated for the same purpose.
> 
> The trigger implementation is bad because it is sending too much requests to devlake, flush out the useful logging and quite annoying. But it help user go through the process little bit smoother, one can observe the progress of all plugins and then see a "Go to Grafana" button after all tasks are done.
> 
> The new method should follow the same steps: trigger / progress / go to grafana . and with a better implementation. Which is not a easy task, so i suggest we do the fast way first, and then work on the new method on next iter.

Current solution is redirect the user to Tasks page to view progress. Something like this:
![image](https://user-images.githubusercontent.com/27032263/140332736-c7235b4e-9a6d-44f7-abc3-2e452a44a787.png)

I suggest we don't need a "View Grafana" stage because we have the "View Dashboards" button in the top left. This would keep it simple. All that is needed is to update "progress" on tasks if "progress < 1" && "status != 'TASK_FAILED'".

**Comment by klesh** [comment]
@kevin-kline simple for us, complicated for user.
New user doesn't know our flow, even if we told he to do so, he would have to jump back and forth between pages, that's not very user friendly.
I suggest that we should arrange our menu base on user maturity  order:
- Configuration(Data Integrations): every one have to do that
- Collect Data(Triggers): trigger > watch progress > link to grafana or a hint for grafana
- Tasks: User got familiar with our system, he want browse in depth

@Startrekzky What do u think?

**Comment by kevin-kline** [comment]
> @kevin-kline simple for us, complicated for user. New user doesn't know our flow, even if we told he to do so, he would have to jump back and forth between pages, that's not very user friendly. I suggest that we should arrange our menu base on user maturity order:
> 
> * Configuration(Data Integrations): every one have to do that
> * Collect Data(Triggers): trigger > watch progress > link to grafana or a hint for grafana
> * Tasks: User got familiar with our system, he want browse in depth
> 
> @Startrekzky What do u think?

Ok I'll start by implementing the old Triggers way, and disabling "Tasks" page again.
