### ISSUE TITLE
README links should be absolute, not relative.

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#786]
## Documentation Scope
If a user is looking at a README locally and not in the browser, some links will not take them to the proper pages because they are relative rather than absolute links.

## Describe the Change
We should change the relative paths to absolute paths.

## Screenshots
![image](https://user-images.githubusercontent.com/27032263/141850767-fbe9458d-733a-4300-b675-b5bae1c48304.png)

**Comment by klesh** [comment]
Those links are internal resources, relative path is perfectly fine, it is fault of VSCode, or whatever tool you are using.
Even if we make all links absolute, what people gain is able to open a Remote Document from a Local Document, that doesn't make sense, besides, the Remote Document might be removed if Local Document were out of sync.
And this would break Mirror repo, especially when user accesses mirror repo because of github was unreachable.

**Comment by joncodo** [comment]
Agreed. We dont need this.
