### ISSUE TITLE
GitHub endpoint must handle url with or without '/'

### ISSUE THREAD

**Issue by mindlesscloud** [merico-dev/lake#804]
## Describe the bug
The endpoint must end with `/` in config-ui, otherwise it would result in a DNS `no such host` error.

When a user edits this in config ui, they have to set end the url with trailing slash. The backend should handle this.

## Screenshots
![image](https://user-images.githubusercontent.com/8455907/142129736-a8a58fc2-eb3c-4b52-bbb1-c60bd2b04ea7.png)

## Additional context
a better way to concatenate url path elements:
```go
endpoint := "https://api.github.com" // This is the value that comes from config-ui
repo := "repo/merico-dev/lake"
u, err := url.Parse(endpoint)
if err != nil{
    // check err
}
u.Path = path.Join(u.Path, repo)
u.String() // the result url
```

**Comment by klesh** [comment]
I think we should do it on iter5

**Comment by joncodo** [comment]
## Assumptions

1. I think we should do this for all urls in all plugins since this could cause problems for other plugins too.
2. There should a core util library for stuff like this so we can share code across plugins?

## Questions

1. I do not see this problem for me locally. When I add a trailing slash in postman, the queries fail. How can I validate this work locally to prove that this is the right way to do things? @mindlesscloud 

FAILS:
<img width="530" alt="Screen Shot 2021-11-17 at 8 24 59 AM" src="https://user-images.githubusercontent.com/3011407/142200197-c60f1c53-9274-4c62-8c85-e65d016f6d7f.png">

WORKS:
<img width="613" alt="Screen Shot 2021-11-17 at 8 25 39 AM" src="https://user-images.githubusercontent.com/3011407/142200265-63570cba-be79-4291-82ab-bc350b44177a.png">

**Comment by joncodo** [comment]
The actual issue we need to solve

- [ ] github and gitlab need to pass url and query params into the DO method
- [ ] The DO method needs to handle this with the "net/url" package


Something like this:

```
package main

import (
    "fmt"
    "log"
    "net/url"
)

func main() {
    
    baseUrl := "https://some-domain.com"
    base, err := url.Parse(baseUrl)
    if err != nil {
        log.Fatal(err)
    }

relativeUrl := "/getsomething/"
    u, err := url.Parse(relativeUrl)
    if err != nil {
        log.Fatal(err)
    }

    queryString := u.Query()
    queryString.Set("id", "1")
    u.RawQuery = queryString.Encode()


    fmt.Println(base.ResolveReference(u))
}

```
