### ISSUE TITLE
Config-ui: Too many user actions on connection settings pages

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#872]
## Description
Right now, when a user is debugging a plugin like Gitlab, they have to click three buttons to save the data. There are also two separate cancel buttons. This is not an intuitive user experience.

<img width="703" alt="Screen Shot 2021-11-26 at 11 19 06 AM" src="https://user-images.githubusercontent.com/3011407/143602078-f0416d0d-cb44-45c9-9a8e-ab7e335fef80.png">

In this screenshot here are the steps the user takes

1. Fill in all the fields
2. Click on test connection and get an error
3. edit the fields again
4. Click on test connection and get success
5. Then click on save connection
6. Then edit the bottom fields and click on save settings

What I want is one button at the bottom called "Save and Test Connection". No cancel button.

When this button is clicked, it tests the connection and provides the toast to say if it worked or not. It also saves everything.

This is one user step vs many as described above.

@Startrekzky @hezyin please approve this design

**Comment by Startrekzky** [comment]
Hi @joncodo, I agree that there're too many user actions and we should get rid of some, not only for this page but configuration pages for other plugins.
However, I don't think the "Test Connection" should be moved to the bottom of the page. 
The scenario you mentioned is 'debugging a collection', but in the scenario of 'adding a new collection', Jira for example, the dropdown list items of the issue mapping and status mapping are got from Jira API, which is based on a successful collection. Hence, we should make sure users 'test connection' first and then do the rest configuration.

My proposal for this has always been 2 separate pages for 'connection' and 'configuration', according to my original design. This makes the info structure much clearer, and users won't be overwhelmed by too many fields on one single page in any of the following scenarios.
1. adding a new collection and configuration 
2. editing the collection of a data source (eg. update token. Users usually don't need to edit both the collection or configuration of a data source)
3. editing the configuration of a data source (eg. mostly for users who added Jira)
4. debugging (as the pages are separated, it's easier to debug if data collection is due to 'connection error' or other bugs.)

The screenshots of the original design:
1. add/edit connection
![image](https://user-images.githubusercontent.com/14050754/143718613-459dfef0-5faa-4d07-95dd-d54cdad25cf0.png)

2. configuration
![image](https://user-images.githubusercontent.com/14050754/143718635-7ba58a05-d250-45f8-86d9-37b98f8a9123.png)

As you can see, there's only 1 Call-to-action button on both 2 pages, which gives users a clear guide to complete the task.

**Comment by klesh** [comment]
I think "Save" and "Test" should be combined, just like **Grafana** data connection settings page

![image](https://user-images.githubusercontent.com/61080/143972583-c3fecdb0-7a67-4683-bdef-af9a7f5d4cf6.png)

**Comment by klesh** [comment]
@Startrekzky Do we have a conclusion?

**Comment by Startrekzky** [comment]
> @Startrekzky Do we have a conclusion? Maybe sum it up and pass it down to development.

I agree that this page has a lot of `actions`, we should have a new design before taking action. What do you have in mind to refine this page @e2corporation ?

**Comment by klesh** [comment]
Will be addressed by #1862
