### ISSUE TITLE
The README.md is stale

### ISSUE THREAD

**Issue by mindlesscloud** [merico-dev/lake#893]
## Describe the bug
The `json` in the `README.md` and `README-zh-CN.md` need to be updated due to the PR: https://github.com/merico-dev/lake/pull/864

## Screenshots
![image](https://user-images.githubusercontent.com/8455907/144062646-000d9945-7a4b-4c86-a481-7ed9aff745fd.png)

**Comment by kevin-kline** [comment]
This is not technically wrong because the Config-UI triggers page still uses this JSON structure...

The following code shows that the textAreaBody where the JSON is written is nested inside an object which the API can consume:

![image](https://user-images.githubusercontent.com/27032263/144118337-a995bcbd-8e5b-4294-a489-6a0c502a34f9.png)

We can update README references to the API itself, but we don't need to change this part of the README IMO.

**Comment by Startrekzky** [comment]
Not a bug
