### ISSUE TITLE
DELETE /pipelines doesn't update DB

### ISSUE THREAD

**Issue by kevin-kline** [merico-dev/lake#906]
## Describe the bug
Our endpoint to cancel pipelines currently does cancel the currently running task but it does not update the DB, and therefore the pipeline continues to the next task. It does not update the DB to say TASK_CANCELLED

## To Reproduce
1. Start dev server
2. Send a POST /pipelines request to trigger collection
3. Send a DELETE /pipelines/:pipelineId request to cancel pipeline
4. See plugin tasks continue (after current task is cancelled)

## Expected behavior
All pipeline tasks get immediately cancelled.

**Comment by klesh** [comment]
1. immediate stop is not possible, some api requests may have been sent out, have to wait for those requests end to make sure resources are fully reclaimed.  So, log keep outputing is expected but data base should be updated with TASK_FAILED status with message like following
![image](https://user-images.githubusercontent.com/61080/144248872-19672503-73e0-4767-a09f-0a577be6df56.png)
2. not all tasks support canceling, like all conversion tasks dont support canceling. So, for this scenario, tasks will be carry out and database will be ended up with status TASK_COMPELETED

This is by design at the moment. However, it may change on next iteration:
1. Add new status named `TASK_CANCELED` for those canceled tasks/pipelines
2. All tasks including conversion tasks support canceling

**Comment by klesh** [comment]
By design, created #919 #920 to follow up on next iter
