### ISSUE TITLE
Add `sprint_issues_burndown` table in domain layer

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#913]
## Description
... so the date in the domain layer can easily support charts such as 'sprint issue burndown chart' and 'issue_requirement_lead_time_by_status'

## Action item

- [ ] add table `sprint_issues_burndown` 

for later
add table `issue_requirement_lead_time_by_status` 

## Linked issue
#700

## Additional context
If the design in #700 changed, the enrichment logic should change accordingly.

**Comment by mindlesscloud** [comment]
## Plan Of Attack
A new table `sprint_issues_burndown` will track issues status changing with time,
which includes columns:

|  columns |  type |  comment |
|---|---|---|
|  sprint_origin_key |  VARCHAR |
| begin_hour  |  INT | UTC time format as `YYYYMMDDHH`, e.g. 2021120616|
|  end_hour |  INT | UTC time format as `YYYYMMDDHH`, e.g. 2021120716|
|  move_in |  INT | counts issues moved into the sprint since `begin_hour` until `end_hour` |
|  move_out | INT  | counts issues moved out from the sprint since `begin_hour` until `end_hour` |
|  remain |  INT | records the number of remained issues at `end_hour` |

- (`sprint_origin_key` ,`end_hour`) is the composite primary key.

- The duration between `begin_hour` and `end_hour` is exact 24 hours, so if `end_hour` is 2021120716, the `begin_hour` would be 2021120616

**Comment by Startrekzky** [comment]
Should add/rename more columns to break this down by issue types:
1. added, added_requirements, added_bugs, added_incidents, added_other_issues
2. removed, removed_requirements, removed_bugs, removed_incidents, removed_other_issues
3. remaining, remaining_requirements, remaining_bugs, remaining_incidents, remaining_other_issues

**Comment by klesh** [comment]
`begin_hour` and `end_hour` should be with type `datetime` i suggest. because most likely they would be used with `DATE` functions.

**Comment by mindlesscloud** [comment]
> `begin_hour` and `end_hour` should be with type `datetime` i suggest. because most likely they would be used with `DATE` functions.

The value of `DATETIME` type would be affected by the timezone setting of MySQL server

**Comment by narrowizard** [comment]
Also, will it be a new table to save remaining_story_points in each day or one more column in `sprint_issues_burndown` ? @mindlesscloud
