### ISSUE TITLE
collect some duplicate data when using gitlab

### ISSUE THREAD

**Issue by likyh** [merico-dev/lake#916]
## Describe the bug
collect some duplicate data when using gitlab.
All db tables have the same bug.

## Screenshots
![image](https://user-images.githubusercontent.com/3294100/144204381-208da3ff-7f3d-4f9b-92ac-3289ae0da5e6.png)

**Comment by likyh** [comment]
This bug hinders my work. Please fix it quickly.

**Comment by kevin-kline** [comment]
> 
I'm looking into this.

It's helpful if you can add "Steps to reproduce" to your bug. That will help track it down. 
Questions:
- Did you just run GitLab plugin once?
- Is it only on merge_request_commits_merge_requests or other tables as well?
- If others, which ones?
- Is it only GitLab?

**Comment by likyh** [comment]
run more than once and not only but all gitlab tables.

**Comment by kevin-kline** [comment]
> 

I'm open to correction, but I can't confirm that this issue is reproducible on other tables other than the join table in the screenshot. If you can, please provide details. 

This leads me to believe it may have something to do with how GORM handles upsert on composite primary keys. I will test further. If my suspicion is correct, then similar join tables in other plugins such as GitHub will have the same problem. I'll keep looking into it.
